disabled = false
languageCode = 'en-US'
languageName = 'English'
title = 'Cosmic Relief' # This will go in the Header as well

# Change single params to "false" to remove from rendering
[params]
  subtitle = "Astrology & Spiritual Insights" # This goes in the header and in the site title

  # PAGES
  [params.homepage]
    preTitle = 'Astrology & Self-Discovery'
    title = "Cosmic Relief"
    intro= """
### "The stars don’t control you, but they can guide you."
___

**Welcome to Cosmic Relief – Your guide to astrology, self-awareness, and cosmic wisdom.** 

Explore deep insights into your birth chart, planetary movements, and the spiritual significance of the cosmos.  
Whether you're a beginner or an experienced seeker, our goal is to help you align with your true path.

Check out our [Astrology Features](#) and [Contact Us](#) for personalized guidance.
        """
    mainButton = "Astrology Features"
    mainButtonRef = "features"
    secondButton = "Contact Us"
    secondButtonRef = "contacts"

  # Blog section (if enabled)
    blogTitle = "Astrology Insights"
    blogButton= "Read More"

[params.office]
  title = "Our Space"
  description = "Discover cosmic wisdom from anywhere. Our astrology insights are accessible worldwide."
  buttonText = "Explore Charts" 
  buttonLink = "#" 
  mapLink = "#" # If you want to add a location, replace this with a Google Maps embed.

[params.contacts]
  title = "Connect With the Cosmos"
  formCallToAction = "Have a question about your birth chart or astrological transits? Reach out!"
  socialCallToAction = "Follow us on social media for daily astrology updates."
  [params.contacts.form]
    formspreeLink = "https://yourformspreelink.com"
    firstname = "First Name*"
    lastname = "Last Name*"
    email = "E-mail*"
    phone = "Phone Number (Optional)"
    Inquiry = "How can we help?"
    submitBtn = "Send Message"

[params.services]
  title = "Astrology Features"
  description = """Cosmic Relief offers personalized astrological insights to help you navigate life's journey.  
  Explore our features below to deepen your connection with the universe."""
  [params.services.list]
    [params.services.list.0]
      title= "Birth Chart Readings"
      description= "Understand your cosmic blueprint and gain clarity on your strengths, challenges, and life path."
    [params.services.list.01]
      title = "Daily & Monthly Forecasts"
      description= "Stay ahead with insights on upcoming planetary transits and how they affect your energy."
    [params.services.list.02]
      title = "Relationship Compatibility"
      description= "Discover how your zodiac placements interact with others for deeper connections."
    [params.services.list.03]
      title = "Spiritual Guidance"
      description= "Learn about astrology’s role in personal growth, meditation, and self-awareness."
    [params.services.list.04]
      title = "Planetary Retrogrades Explained"
      description= "Unravel the mystery of Mercury Retrograde and other planetary shifts."
    [params.services.list.05]
      title = "Astrology & Career"
      description= "Find alignment between your professional life and cosmic influences."
    [params.services.list.06]
      title = "Custom Reports"
      description= "Get detailed astrology readings tailored to your unique needs."

[params.socials]
  enabled = true
  callToAction= "Follow us for daily astrology insights!"
      [[params.socials.link]]
        name = "instagram"
        link = "https://instagram.com/"
      [[params.socials.link]]
        name = "twitter"
        link = "https://twitter.com/"
      [[params.socials.link]]
        name = "tiktok"
        link = "https://tiktok.com/"
      [[params.socials.link]]
        name = "spotify"
        link = "https://open.spotify.com/show/4Wezn7cIsREL4nI550Nq4v?si=c2adfd75580e44a1"

[params.schedules]
  enabledFooter = false
  enabledContacts = true
  title = "Cosmic Office Hours"
  [params.schedules.days]
    day1 = "Monday: 9am – 7pm"
    day2 = "Tuesday: 9am – 7pm"
    day3 = "Wednesday: 9am – 7pm"
    day4 = "Thursday: 9am – 7pm"
    day5 = "Friday: 9am – 7pm"
    day6 = "Saturday: 10am – 5pm"
    day7 = "Sunday: Closed"

[params.footer]
  extraDescription1 = "Your cosmic guide to astrology & self-discovery."
  extraDescription2 = "Copyright © 2025 Cosmic Relief"
  [params.footer.navigate]
  heading = "Explore"
  [params.footer.contacts]
  enabled = true
  heading = "Contact Cosmic Relief"
  address = "Globally Available"
  mail = "hello@cosmicrelief.com"
  mail2 = "support@cosmicrelief.com"
  phone = "+00 0000000"

[params.notfound]
  title = "404 - Lost in Space?"

[params.single]
  similarContent= "Related Astrology Insights"
  toc= "Table of Contents"

[menus]
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

  [[menus.main]]
  name = "Astrology Features"
  pageRef = "features"
  url = "/features/"
  weight = 2

  [[menus.main]]
  name = "About"
  pageRef = "about"
  url = "/about/"
  weight = 3

  [[menus.main]]
  name = "Contact"
  pageRef = "contacts"
  url = "/contacts/"
  weight = 4

  [[menus.main]]
  name = "Podcast"
  url = "https://open.spotify.com/show/4Wezn7cIsREL4nI550Nq4v?si=c2adfd75580e44a1"
  weight = 5

